# This workflow will build, format, and lint a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format
      - name: Restore dependencies
        run: dotnet restore
      - name: Format code
        run: dotnet format --verbosity normal
      - name: Build
        run: dotnet build --no-restore --verbosity normal
