name: .NET

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Format code
        run: dotnet format SI514.csproj --verbosity normal

      - name: Build
        run: dotnet build --no-restore --verbosity normal
