name: Next.JS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        working-directory: ./beauty-salon

      - name: Lint the project
        run: bun run lint
        working-directory: ./beauty-salon

      - name: Build the project
        run: bun run build
        working-directory: ./beauty-salon
